---
title: "asthma_analysis"
bibliography: /Users/asingh/Dropbox/Manuscript/diablo/mybib.bib
thanks: "Replication files are available at https://github.com/singha53/diablo"
output:
  html_document:
    toc: yes
    theme: united
    highlight: tango
    keep_md: yes
biblio-style: /Users/asingh/Dropbox/Manuscript/diablo/genome-biology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, tidy = TRUE)

WhereAmI <- "/Users/asingh/Dropbox/Manuscript/diablo/analyses/casestudy2_asthma/"

# load libraries
library(corrplot)
library(pROC)
library(amritr)
library(tidyverse)
library(mixOmics)
library(NMF)
library(RColorBrewer)
library(cowplot)
library(scales)
library(UpSetR)

## load data
load(paste0(WhereAmI, "data/asthmaDatasets.RDATA"))
## clean datasets
cells <- cells[, c("Relative.Neutrophils","Relative.Lymphocytes","Relative.Monocytes",
  "Relative.Eosinophils","Relative.Basophils","Treg","Tcells","Bcells","Th17")]
metExp <- metExp[apply(metExp, 1, mad) >0, ]
rownames(metExp) <- metabolites[rownames(metExp), "BIOCHEMICAL"]

## identify any overlapping gene and metabolite modules names
colnames(gene.module)[colnames(gene.module) %in% intersect(colnames(gene.module), colnames(metabolite.module))] <- 
  paste("genMod", colnames(gene.module)[colnames(gene.module) %in% intersect(colnames(gene.module), colnames(metabolite.module))], sep = "-")

```

\pagebreak

# FEV1 profiles

```{r}
fev1 <- read.csv(paste0(WhereAmI, "data/fev1Data.csv"), row.names = 1)[, c("BLFEV","F10L","F20L","F30L","F45L","F60L","F90L","F120L","F180L","F240L","F300L","F360L","F420L")]

p <- scale(t(fev1), center = fev1$BLFEV, scale = fev1$BLFEV) %>% as.data.frame() %>%
  tbl_df() %>%
  mutate(Time = c(0, 10, 20, 30, 45, 60, 90, 120, 180 ,240, 300, 360, 420)) %>%
  tidyr::gather(Subject, FEV1, -Time) %>%
  filter(Time %in% c(0, 10, 20, 30, 45, 60, 90, 120)) %>%
  mutate(fev1 = 100*FEV1) %>%
  ggplot(aes(x = Time, y = fev1, fill = Subject, color = Subject)) +
  geom_point() + geom_line(color="black")
  
#pdf(paste0(WhereAmI, "7-Figure6_asthmaAnalysis/Figure6A.pdf"))
p + scale_y_continuous(expression('Percent drop in '~ FEV[1])) + theme_bw() +
  scale_x_continuous(expression('Time (minutes)')) +
  theme(axis.text.y = element_text(size = 15, hjust = 1)) + theme(axis.text.x = element_text(size = 15, hjust = 0.5))+
  theme(axis.title.x=element_text(size = 15)) + theme(axis.title.y=element_text(size = 15,angle = 90))+ 
  theme(legend.key = element_rect(colour = "black", fill="white"))  +
  theme(plot.background = element_rect()) +  
  theme(strip.background = element_rect(colour = "black", fill = "white",
                                        size = 1), strip.text.x = element_text(size=20)) +
  geom_hline(yintercept = 0, colour="yellow3", linetype = "longdash") +
  theme(legend.position="none")
#dev.off()
```

# DIABLO

## tune keepX

```{r, fig.height=10}
X <- list(cells=cells, gene.module=gene.module, metabolite.module=metabolite.module)
time <- demo$Time
Cov <- data.frame(sample = rep(1:14, 2), time = demo$Time)
A = lapply(X, function(i) suppressMessages(withinVariation(X = i, design = Cov)))

## run DIABLO
ncomp <- 2
design <- matrix(1, nrow = 3, ncol = 3)
diag(design) <- 0
```

## error rate of optimal keepX

```{r}
keepX = list(cells = c(3, 3), gene.module = c(5, 5), metabolite.module = c(5, 5))
ncomp = 2
sample = rep(1:14, 2)
time = demo$Time
Y = time

leave.one.out.cv = function(X, Y, ncomp, keepX, design, sample){
  
  averageVotes_unpaired <- averageVotes_paired <- list()

  for(rm in 1 : length(unique(sample))){
    sequence <- which(rm == sample)
    trainX <- lapply(X, function(i) i[-sequence, ])
    trainY <- Y[-sequence]
    xtest <- lapply(X, function(i) i[sequence, ])
	  xwtest <- lapply(X, function(i) i[sequence, ]-matrix(colMeans(i[sequence,]),ncol=ncol(i),nrow=length(sequence),byrow=TRUE))
	  samplew <- sample[-sequence]
    
	  Cov <- data.frame(sample=samplew, stimu=trainY)
	  trainXw <-  lapply(trainX, function(i){
	    withinVariation(i, Cov)
	  })

	  ## unpaired diablo
	  diablo_unpaired = block.splsda(X = trainX, Y = trainY, ncomp = ncomp, keepX = keepX, design = design)
    test_unpaired = predict(diablo_unpaired, xtest, method = "all")
	  averageVotes_unpaired[[rm]] <- test_unpaired$AveragedPredict[,,2][,1]
	  
	  ## paired diablo
	  diablo_paired = block.splsda(X = trainXw, Y = trainY, ncomp = ncomp, keepX = keepX, design = design)
    test_paired = predict(diablo_paired, xwtest, method = "all")
	  averageVotes_paired[[rm]] <- test_paired$AveragedPredict[,,2][,1]
  }
  avgVote <-  list(unpaired = unlist(averageVotes_unpaired), paired=unlist(averageVotes_paired))
  avgVote <- lapply(avgVote, function(i){
    roc.score = roc(response = sapply(strsplit(names(unlist(averageVotes_unpaired)), "\\."), function(i) i[3]), predictor = i, plot = FALSE, percent = TRUE, na.rm =TRUE)
    roc.res = data.frame(Specificity = rev(roc.score$specificities), Sensitivity = rev(roc.score$sensitivities))
    roc.res$fp = 100 - as.numeric(roc.res$Specificity)
    roc.res$tp = as.numeric(roc.res$Sensitivity)
    auc=roc.score$auc
    return(list(roc.res=roc.res, auc=auc))
  })
avgVote
}

cv <- leave.one.out.cv(X, Y, ncomp, keepX, design, sample)

aucPlot <- rbind(cv$unpaired$roc.res, cv$paired$roc.res) %>% 
  mutate(Time = c(rep("DIABLO", nrow(cv$unpaired$roc.res)), rep("DIABLOw", nrow(cv$paired$roc.res)))) %>% 
  ggplot(aes(x = fp, y = tp, fill = Time, color = Time)) +
  geom_abline(intercept = 0, slope = 1, col = "gray", linetype="dashed")  +
  geom_point() +
  geom_line() +
  customTheme(sizeStripFont = 15, xAngle = 0, hjust = 0.5, 
    vjust = 0.5, xSize = 20, ySize = 20, xAxisSize = 20, yAxisSize = 20) +
  xlab("100 - Specificity") + ylab("Sensitivity") +
  annotate("text", label = paste0("AUC = ", round(cv$unpaired$auc, 1), "%"), x = 75, y = 50, size = 5, colour = hue_pal()(2)[2]) +
  annotate("text", label = paste0("AUC = ", round(cv$paired$auc, 1), "%"), x = 35, y = 85, size = 5, colour = hue_pal()(2)[1]) +
  theme(legend.position = c(0.7, 0.15))

```

## diablo - unpaired and paired

```{r}
# unpaired
diablo = block.splsda(X = X, Y = time, ncomp = ncomp, keepX = keepX, design = design)
diabloPanel <- list(cells = c(selectVar(diablo, comp = 1)$cells$name, 
                              selectVar(diablo, comp = 2)$cells$name),
                           gene.module = c(selectVar(diablo, comp = 1)$gene.module$name,  
                                           selectVar(diablo, comp = 2)$gene.module$name),
                           metabolite.module = c(selectVar(diablo, comp = 1)$metabolite.module$name, 
                                                 selectVar(diablo, comp = 2)$metabolite.module$name))

# paired
diablow = block.splsda(X = A, Y = time, ncomp = ncomp, keepX = keepX, design = design)
diablowPanel <- list(cells = c(selectVar(diablow, comp = 1)$cells$name, 
                              selectVar(diablo, comp = 2)$cells$name),
                           gene.module = c(selectVar(diablow, comp = 1)$gene.module$name,  
                                           selectVar(diablow, comp = 2)$gene.module$name),
                           metabolite.module = c(selectVar(diablow, comp = 1)$metabolite.module$name, 
                                                 selectVar(diablow, comp = 2)$metabolite.module$name))


```

# Component plots

```{r}
dat <- as.data.frame(Reduce("+", diablo$variates)/length(X)) %>% 
  mutate(time = time, sample = factor(sample))
p1 <- ggplot(dat, aes(x = `comp 1`, y = `comp 2`, group = time, color = time)) +
  geom_point(size = 4) +
  stat_ellipse() +
  geom_line(aes(group = sample), color = "gray")+
  customTheme(sizeStripFont = 15, xAngle = 0, hjust = 0.5, vjust = 0.5, 
              xSize = 20, ySize = 20, xAxisSize = 20, yAxisSize = 20) +
  xlab("Consensus Component 1") +
  ylab("Consensus Component 2") +
  ggtitle("DIABLO") +
  theme(legend.position = c(0.1, 0.9)) + 
  scale_color_manual(values=c("#388ECC", "#F68B33"))
  

dat <- as.data.frame(Reduce("+", diablow$variates)/length(X)) %>% 
  mutate(time = time, sample = factor(sample))
p2 <- ggplot(dat, aes(x = `comp 1`, y = `comp 2`, group = time, color = time)) +
  geom_point(size = 4) +
  stat_ellipse() +
  geom_line(aes(group = sample), color = "gray")+
  customTheme(sizeStripFont = 15, xAngle = 0, hjust = 0.5, vjust = 0.5, 
              xSize = 20, ySize = 20, xAxisSize = 20, yAxisSize = 20) +
  xlab("Consensus Component 1") +
  ylab("Consensus Component 2") +
  ggtitle("DIABLOw") +
  theme(legend.position = "none") + 
  scale_color_manual(values=c("#388ECC", "#F68B33"))

pdf(paste0(WhereAmI, "results/Figures/auc_componentPlot.pdf"), width = 13, height = 4)
plot_grid(aucPlot, p1, p2, ncol = 3)
dev.off()

```

## compare multi-omic panels

```{r}
diablowPanel_modif <- diablowPanel
diablowPanel_modif$gene.module[diablowPanel_modif$gene.module == "Valine, leucine and isoleucine biosynthesis"] <- "Valine, leucine and isoleucine metabolism"
diablowPanel_modif$gene.module[diablowPanel_modif$gene.module == "genMod-Tryptophan metabolism"] <- "Tryptophan metabolism"

panels <-  list(DIABLO_Cells = diabloPanel$cells, 
                   `DIABLO_Gene modules` = diabloPanel$gene.module, 
                   `DIABLO_Metabolite modules` = diabloPanel$metabolite.module,
                   DIABLOw_Cells = diablowPanel_modif$cells, 
                   `DIABLOw_Gene modules` = diablowPanel_modif$gene.module, 
                   `DIABLOw_Metabolite modules` = diablowPanel_modif$metabolite.module)

intersect(panels$`DIABLOw_Gene modules`, panels$`DIABLOw_Metabolite modules`)

input <- fromList(panels)
metadata <- data.frame(panels=names(panels),
  type = c(rep("DIABLO", 3), rep("DIABLOw", 3)))

library(grid)

#brewer.pal(2, "Pastel1")
png(paste0(WhereAmI, "results/Figures/overlap.png"), width = 7, height = 4, units = 'in', res = 300)
upset(input, sets = colnames(input), keep.order = TRUE,
    queries = list(list(query = intersects, params = list("DIABLOw_Gene modules","DIABLOw_Metabolite modules"), active = TRUE, color = "maroon"),
      list(query = intersects, params = list("DIABLOw_Gene modules","DIABLOw_Metabolite modules","DIABLO_Metabolite modules"), active = TRUE, color = "maroon")),
  set.metadata = list(data = metadata, plots = list(list(type = "matrix_rows", 
    column = "type", colors = c(DIABLO = "#FBB4AE", DIABLOw = "#B3CDE3"), 
    alpha = 0.5))))
dev.off()


```

# heatmap

```{r, fig.height=7, fig.width=7}
corMat <- mapply(function(x, y){
  x[, unique(y)]
}, x = A, y = diablowPanel) %>% 
  do.call(cbind, .) %>% 
  cor

color.blocks = brewer.pal(n = 12, name = "Set2")[1:3]
row.sideColors = rep(color.blocks, sapply(lapply(diablowPanel, unique), length))
col.sideColors = row.sideColors

pdf(paste0(WhereAmI, "results/Figures/varCor.pdf"), width = 15, height = 15)
cim(corMat, margins = c(35, 35), row.cex = 2, col.cex = 2, 
  row.sideColors=row.sideColors, col.sideColors=col.sideColors)
legend("topright", names(diablowPanel), col = color.blocks, pch = 19, bty = "n", cex = 2)
dev.off()


```

# circosplot

```{r}
pdf(paste0(WhereAmI, "results/Figures/circosPlot.pdf"), width = 15, height = 15)
circosPlot(diablow, cutoff = 0.8, showIntraLinks = FALSE, size.variables = 1, size.labels = 2, size.legend = 2, color.blocks = color.blocks)
dev.off()

```

