---
title: "asthma_analysis"
output:
  html_document:
    toc: yes
    theme: united
    highlight: tango
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, tidy = TRUE)

WhereAmI <- "~/Dropbox/PROOF/Manuscript/mixOmics/diablo/analyses/casestudy2_asthma/"

# load libraries
library(corrplot)
library(pROC)
library(amritr)
library(tidyverse)
library(mixOmics)
library(NMF)
library(RColorBrewer)
library(cowplot)
library(scales)
library(UpSetR)
library(org.Hs.eg.db)
library(KEGG.db)
library(annotate)
library("hugene10sttranscriptcluster.db")
library(grid)
source(paste0(WhereAmI, "asthma_functions.R"))

## load data
load("~/Dropbox/PROOF/Manuscript/mixOmics/diablo_datasets/asthma/asthmaDatasets.RDATA")
## clean datasets
cells <- cells[, c("Relative.Neutrophils","Relative.Lymphocytes","Relative.Monocytes",
  "Relative.Eosinophils","Relative.Basophils","Treg","Tcells","Bcells","Th17")]
metExp <- metExp[apply(metExp, 1, mad) >0, ]
rownames(metExp) <- metabolites[rownames(metExp), "BIOCHEMICAL"]

## identify any overlapping gene and metabolite modules names
colnames(gene.module)[colnames(gene.module) %in% intersect(colnames(gene.module), colnames(metabolite.module))] <- 
  paste("genMod", colnames(gene.module)[colnames(gene.module) %in% intersect(colnames(gene.module), colnames(metabolite.module))], sep = "-")

```

\pagebreak

## FEV1 profiles

```{r fev1Plots, fig.path='Figures/', dev='png', fig.height = 5, fig.width = 7}
fev1 <- read.csv("~/Dropbox/PROOF/Manuscript/mixOmics/diablo_datasets/asthma/fev1Data.csv", row.names = 1)[, c("BLFEV","F10L","F20L","F30L","F45L","F60L","F90L","F120L","F180L","F240L","F300L","F360L","F420L")]

p <- scale(t(fev1), center = fev1$BLFEV, scale = fev1$BLFEV) %>% as.data.frame() %>%
  tbl_df() %>%
  mutate(Time = c(0, 10, 20, 30, 45, 60, 90, 120, 180, 240, 300, 360, 420)) %>%
  tidyr::gather(Subject, FEV1, -Time) %>%
  filter(Time %in% c(0, 10, 20, 30, 45, 60, 90, 120)) %>%
  mutate(Time = Time/60) %>% 
  mutate(fev1 = 100*FEV1) %>%
  ggplot(aes(x = Time, y = fev1, group = Subject)) +
  geom_point() + geom_line(color="black") +
  scale_y_continuous(expression('Percent drop in '~ FEV[1])) + theme_bw() +
  scale_x_continuous(expression('Time (hours)')) +
  theme(axis.text.y = element_text(size = 15, hjust = 1)) + theme(axis.text.x = element_text(size = 15, hjust = 0.5))+
  theme(axis.title.x=element_text(size = 15)) + theme(axis.title.y=element_text(size = 15,angle = 90))+ 
  theme(legend.key = element_rect(colour = "black", fill="white"))  +
  theme(plot.background = element_rect()) +  
  theme(strip.background = element_rect(colour = "black", fill = "white",
                                        size = 1), strip.text.x = element_text(size=20)) +
  geom_hline(yintercept = 0, colour="yellow3", linetype = "longdash") +
  theme(legend.position="none")

p
```

## DIABLO

### tune keepX

```{r}
X <- list(cells=cells, gene.module=gene.module, metabolite.module=metabolite.module)
time <- demo$Time
Cov <- data.frame(sample = rep(1:14, 2), time = demo$Time)
A = lapply(X, function(i) suppressMessages(withinVariation(X = i, design = Cov)))

lapply(A, dim)

## run DIABLO
ncomp <- 2
design <- matrix(1, nrow = 3, ncol = 3)
diag(design) <- 0
```

### error rate of optimal keepX

```{r aucPlot, fig.path='Figures/', dev='png', fig.height = 7, fig.width = 7}
keepX = list(cells = c(3, 3), gene.module = c(5, 5), metabolite.module = c(5, 5))
ncomp = 2
sample = rep(1:14, 2)
time = demo$Time
Y = time

cv <- leave.one.out.cv(X, Y, ncomp, keepX, design, sample)

aucPlot <- rbind(cv$unpaired$roc.res, cv$paired$roc.res) %>% 
  mutate(Time = c(rep("DIABLO", nrow(cv$unpaired$roc.res)), rep("mDIABLO", nrow(cv$paired$roc.res)))) %>% 
  ggplot(aes(x = fp, y = tp, fill = Time, color = Time)) +
  geom_abline(intercept = 0, slope = 1, col = "gray", linetype="dashed")  +
  geom_point() +
  geom_line() +
  customTheme(sizeStripFont = 15, xAngle = 0, hjust = 0.5, 
    vjust = 0.5, xSize = 20, ySize = 20, xAxisSize = 20, yAxisSize = 20) +
  xlab("100 - Specificity") + ylab("Sensitivity") +
  annotate("text", label = cv$unpaired$auc, x = 75, y = 50, size = 3.5, colour = hue_pal()(2)[1]) +
  annotate("text", label = cv$paired$auc, x = 35, y = 85, size = 3.5, colour = hue_pal()(2)[2]) +
  theme(legend.position = c(0.7, 0.15))
aucPlot
```

### diablo - unpaired and paired

```{r}
# unpaired
diablo = block.splsda(X = X, Y = time, ncomp = ncomp, keepX = keepX, design = design)
diabloPanel <- list(cells = c(selectVar(diablo, comp = 1)$cells$name, 
                              selectVar(diablo, comp = 2)$cells$name),
                           gene.module = c(selectVar(diablo, comp = 1)$gene.module$name,  
                                           selectVar(diablo, comp = 2)$gene.module$name),
                           metabolite.module = c(selectVar(diablo, comp = 1)$metabolite.module$name, 
                                                 selectVar(diablo, comp = 2)$metabolite.module$name))

# paired
diablow = block.splsda(X = A, Y = time, ncomp = ncomp, keepX = keepX, design = design)
diablowPanel <- list(cells = c(selectVar(diablow, comp = 1)$cells$name, 
                              selectVar(diablow, comp = 2)$cells$name),
                           gene.module = c(selectVar(diablow, comp = 1)$gene.module$name,  
                                           selectVar(diablow, comp = 2)$gene.module$name),
                           metabolite.module = c(selectVar(diablow, comp = 1)$metabolite.module$name, 
                                                 selectVar(diablow, comp = 2)$metabolite.module$name))

```

### Component plots

```{r auc_componentPlot, fig.path='Figures/', dev='png', fig.height = 4, fig.width = 13}
dat <- as.data.frame(Reduce("+", diablo$variates)/length(X)) %>% 
  mutate(time = time, sample = factor(sample))
p1 <- ggplot(dat, aes(x = `comp 1`, y = `comp 2`, group = time, color = time)) +
  geom_point(size = 4) +
  stat_ellipse() +
  geom_line(aes(group = sample), color = "gray")+
  customTheme(sizeStripFont = 15, xAngle = 0, hjust = 0.5, vjust = 0.5, 
              xSize = 20, ySize = 20, xAxisSize = 20, yAxisSize = 20) +
  xlab("Consensus Component 1") +
  ylab("Consensus Component 2") +
  ggtitle("DIABLO") +
  theme(legend.position = c(0.1, 0.9)) + 
  scale_color_manual(values=c("#388ECC", "#F68B33"))
  

dat <- as.data.frame(Reduce("+", diablow$variates)/length(X)) %>% 
  mutate(time = time, sample = factor(sample))
p2 <- ggplot(dat, aes(x = `comp 1`, y = `comp 2`, group = time, color = time)) +
  geom_point(size = 4) +
  stat_ellipse() +
  geom_line(aes(group = sample), color = "gray")+
  customTheme(sizeStripFont = 15, xAngle = 0, hjust = 0.5, vjust = 0.5, 
              xSize = 20, ySize = 20, xAxisSize = 20, yAxisSize = 20) +
  xlab("Consensus Component 1") +
  ylab("Consensus Component 2") +
  ggtitle("mDIABLO") +
  theme(legend.position = "none") + 
  scale_color_manual(values=c("#388ECC", "#F68B33"))

plot_grid(aucPlot, p1, p2, ncol = 3)

```

## compare multi-omic panels

```{r overlap, fig.path='Figures/', dev='png', fig.height = 4, fig.width = 7}
diablowPanel_modif <- diablowPanel
diablowPanel_modif$gene.module[diablowPanel_modif$gene.module == "Valine, leucine and isoleucine biosynthesis"] <- "Valine, leucine and isoleucine metabolism"
diablowPanel_modif$gene.module[diablowPanel_modif$gene.module == "genMod-Tryptophan metabolism"] <- "Tryptophan metabolism"

panels <-  list(DIABLO_Cells = diabloPanel$cells, 
                   `DIABLO_Gene modules` = diabloPanel$gene.module, 
                   `DIABLO_Metabolite modules` = diabloPanel$metabolite.module,
                   mDIABLO_Cells = diablowPanel_modif$cells, 
                   `mDIABLO_Gene modules` = diablowPanel_modif$gene.module, 
                   `mDIABLO_Metabolite modules` = diablowPanel_modif$metabolite.module)

intersect(panels$`mDIABLO_Gene modules`, panels$`mDIABLO_Metabolite modules`)

input <- fromList(panels)
metadata <- data.frame(panels=names(panels),
  type = c(rep("DIABLO", 3), rep("mDIABLO", 3)))

upset(input, sets = colnames(input), keep.order = TRUE,
    queries = list(list(query = intersects, params = list("mDIABLO_Gene modules","mDIABLO_Metabolite modules"), active = TRUE, color = "maroon"),
      list(query = intersects, params = list("mDIABLO_Gene modules","mDIABLO_Metabolite modules","DIABLO_Metabolite modules"), active = TRUE, color = "maroon")),
  set.metadata = list(data = metadata, plots = list(list(type = "matrix_rows", 
    column = "type", colors = c(DIABLO = "#FBB4AE", DIABLOw = "#B3CDE3"), 
    alpha = 0.5))))

```

### heatmap

```{r varCor, fig.path='Figures/', dev='png', fig.height = 15, fig.width = 15}
corMat <- mapply(function(x, y){
  x[, unique(y)]
}, x = A, y = diablowPanel) %>% 
  do.call(cbind, .) %>% 
  cor

color.blocks = brewer.pal(n = 12, name = "Set2")[1:3]
row.sideColors = rep(color.blocks, sapply(lapply(diablowPanel, unique), length))
col.sideColors = row.sideColors

cim(corMat, margins = c(35, 35), row.cex = 2, col.cex = 2, 
  row.sideColors=row.sideColors, col.sideColors=col.sideColors)
legend("topright", names(diablowPanel), col = color.blocks, pch = 19, bty = "n", cex = 2)

```

### circosplot

```{r circosPlot, fig.path='Figures/', dev='png', fig.height = 15, fig.width = 15}
circosPlot(diablow, cutoff = 0.8, showIntraLinks = FALSE, size.variables = 1, size.labels = 2, size.legend = 2, color.blocks = color.blocks)
```

### Asthma KEGG pathway

```{r Asthma_pathwayGenes, fig.path='Figures/', dev='png', fig.height = 7, fig.width = 7}
## obtain KEGG id for the Asthma pathway
xx <- as.list(KEGGPATHID2NAME)
hsaID <- unlist(xx)[unlist(xx)=="Asthma"]

## extract the entrez gene ids for members of the Asthma pathway
kegg <- org.Hs.egPATH2EG
entrez <- unlist(as.list(kegg[names(hsaID)]))

## map entrez ids to affymetrix probe set ids
eg <- getEG(rownames(genExp), "hugene10sttranscriptcluster")
geneIDs <- eg[eg %in% entrez]

## extract expression data for genes in the asthma pathway
genesDat <- genExp[names(geneIDs), ]
dim(genesDat)

pval <- apply(genesDat, 1, function(i){
  t.test(i[demo$Time == "post"], i[demo$Time == "pre"], paired = TRUE)$p.value
})
padj <- p.adjust(pval, "BH")
fc <- apply(genesDat, 1, function(i){
 mean(i[demo$Time == "post"]) - mean(i[demo$Time == "pre"])
})


plot(-log10(pval) ~ fc, pch = 19, col = 2, xlim = c(-0.17, 0.155),
     ylab=expression("-log"[10]~~~"p-value"), xlab = expression("log"[2]~~~"fold-change"),
     main = "Asthma KEGG pathway")
points(-log10(pval) ~ fc, pch = 21)
text(x = fc, y = -log10(pval), labels = getSYMBOL(names(pval), "hugene10sttranscriptcluster"),
     cex = 0.6, pos = 1:4)
abline(h = -log10(0.05), lty = 2)
text(x = -0.10, y = -log10(0.045), labels = "P-value = 0.05")

```

